
"""validate

Revision ID: a6a615a7dd9d
Revises: 883111ac6470
Create Date: 2024-05-22 15:14:37.424387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6a615a7dd9d'
down_revision: Union[str, None] = '883111ac6470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('is_validate', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'is_validate')
    # ### end Alembic commands ###
