
"""price float

Revision ID: dbca05a6cd6b
Revises: a6a615a7dd9d
Create Date: 2024-05-22 15:23:40.089020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbca05a6cd6b'
down_revision: Union[str, None] = 'a6a615a7dd9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'price',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'price',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
